version: "3.7"

services:
  postgres:
    image: postgres:10.1-alpine
    container_name: school-bot-postgres
    volumes:
      - school-bot-postgres:/var/lib/postgresql/data/
    env_file:
      - postgres.env
    ports:
      - "8762:5432"

  redis:
    image: redis:alpine3.14
    container_name: school-bot-redis
    volumes: 
      - school-bot-redis:/data
    env_file:
      - redis.env
    ports:
      - "3697:6379"
    command: redis-server --appendonly yes
volumes: 
  school-bot-postgres:
  school-bot-redis: